export enum FileUploadStatus {
  COMPLETED = 'COMPLETED',
  PARTIALLY_COMPLETED = 'PARTIALLY_COMPLETED',
  DELETED = 'DELETED',
  ARCHIVED = 'ARCHIVED',
  FAILED = 'FAILED',
  PROCESSING = 'PROCESSING',
  PENDING = 'PENDING'
}

export enum ApiStatus {
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR'
}